import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import ShoppingBagIcon from "@mui/icons-material/ShoppingBag";
import FavoriteIcon from "@mui/icons-material/Favorite";
import ShoppingCartIcon from "@mui/icons-material/ShoppingCart";

import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " flex flex-col justify-between min-h-dvh w-dvw pt-28 md:pt-36"
        }
      >
        <header className="fixed top-0 w-dvw flex items-center md:flex-col md:justify-between bg-yellow-500 h-16 md:h-32">
          <div className="flex items-center justify-between w-5/6 md:w-full md:h-1/2 px-6">
            <div>
              <Link
                href={"/"}
                className="flex items-end leading-none text-xl capitalize"
              >
                <ShoppingBagIcon />
                <h1>AllCart</h1>
              </Link>
            </div>
            <div>
              <Link href={"/cart"}>
                <ShoppingCartIcon />
                <p></p>
              </Link>
            </div>
          </div>
          <NavBar />
        </header>
        <main className="h-full">{children}</main>
        <footer className="flex-col items-center justify-center w-dvw py-6 bg-slate-200">
          <div className="flex justify-center">
            <Link href={"/"} className="flex leading-none items-end text-xl">
              <ShoppingBagIcon />
              <h1>AllCart</h1>
            </Link>
          </div>
          <div className="flex justify-center">
            &copy; {new Date().getFullYear()} — AllCart Inc.
          </div>
          <div className="flex justify-center">
            <p>
              Built with <FavoriteIcon type="" /> and {` `}
              <a href="https://nextjs.org" target="_blank">
                Next.js
              </a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
